[project]
name = "aipod-demo"
version = "0.1.0"
description = "Examples of how LLMs can be used to process and analyze podcasts"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai",
    "llama-index",
    "google-generativeai",
    "streamlit"
]
